### ISSUE TITLE
Error Mesage since Update JS-Controller to 3.1.4

### ISSUE THREAD

**Issue by zuerom** [jpgorganizer/ioBroker.smartgarden#11]
Hi, i Updated my JS-Controller to 3.1.4, since then i got the following Error Mesage:
startInstance system.adapter.smartgarden.0: required adapter "@jpgorganizer/utils" not found!

after that i tried to uninstall it, and manually install  the jporganizer...
npm install https://github.com/jpgorganizer/ioBroker.utils
but i get Warnings and nothing works...

npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

then i tried to install the newst  smartgarden again... (0.6.0

But i got the same Warn-Messages...
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

please help me... before it workd like charm...

**Comment by jpgorganizer** [comment]
You updated your js-c from which version?

How did you reinstall the new adapter version? Via command line or via iobroker admin interface?

You install on a RaspberryPI, right?

Currently I have no idea whats wrong with your install. But let's see

r jgporganizer

**Comment by zuerom** [comment]
...i don't know anymore but something like 2.x
...i tried both, but in iobroker admin doesn't happen anything.
...yes it's an installation on RaspPI (4 Months ago)

**Comment by jpgorganizer** [comment]
>>> ...i tried both, but in iobroker admin doesn't happen anything.
but your error messages from the first post are from commandline ?

**Comment by zuerom** [comment]
Yes

**Comment by zuerom** [comment]
If you want we can try a remote-Session like Teamviewer?

**Comment by jpgorganizer** [comment]
I currently have no installation with js-c v3 available. But it works with v3 as some users reported.

> no such file or directory, open '/home/pi/package.json'
I assume that you started the command not from the correct directory, for a RPI  it would be ´/opt/iobroker´

**Comment by jpgorganizer** [comment]
no feedback = no problem = closed

**Comment by zuerom** [comment]
You are right, it works now!

As you wrote i tried in the wrong directory...
-Sorry for my late answer.
zuerom
