### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by Marshammer** [jpgorganizer/ioBroker.smartgarden#13]
Hallo,
bei mir kommt immer error 403. jemand eine Idee das das sein kann?
DANKE 
<img width="1090" alt="Bildschirmfoto 2020-05-29 um 09 50 09" src="https://user-images.githubusercontent.com/66111826/83235260-e60a8380-a191-11ea-99c0-768062adc861.png">

**Comment by jpgorganizer** [comment]
403 deutet auf falsche Zugangsdaten hin.

**Comment by Marshammer** [comment]
Kann nicht sein komme mit den gleichen Daten bei Husqvarna auf die Seite.
Noch eine Idee ? Danke

**Comment by Marshammer** [comment]
so neuer Fehler :) 
die Base adresse hatte nicht gestimmt.

<img width="1094" alt="Bildschirmfoto 2020-05-30 um 13 09 59" src="https://user-images.githubusercontent.com/66111826/83326771-ec266000-a276-11ea-8109-11db20e27da2.png">

**Comment by jpgorganizer** [comment]
Gardena liefert keine Geräte zurück. 

Gleiches Konto genutzt wie in der Gardena App?
Geräte sind eingebunden?

**Comment by Marshammer** [comment]
Ja hab jetzt Extra noch mal das Passwort geändert um zu schauen das alles gleich ist.
Hab Aktuell ein Sensor und ein Wasserhahn in der APP,.

**Comment by jpgorganizer** [comment]
API keys verbunden?

**Comment by jpgorganizer** [comment]
Kannst du ggfs ein python3 Script ausführen?

**Comment by Marshammer** [comment]
APi sollte verbinden sein hab alles gemacht wie in der Anleitung.
Sorry mit Python3 kenne ich mich nicht mit aus. Könnte dir anbieten wenn du es machen würden eine Teams Einladung zu schicken und du schaust es dir bei mir an?

**Comment by jpgorganizer** [comment]
mmh, irgendwie kam mir das jetzt bekannt vor .... schau mal hier
https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/82

**Comment by Marshammer** [comment]
Ich hab jetzt das ganze gardena System noch mal neu unter einer andern Email angelegt.
Immer noch nix gleicher Fehler mit no Data.
Ich glaub ich bin einfach zu blöd :(

**Comment by jpgorganizer** [comment]
warte einfach mal ab, evtl. braucht auch das Gardena Backend ein bisschen Zeit. Sind die Geräte neu?

**Comment by Marshammer** [comment]
Ja waren neu hatte es letzte Woche installiert. 
Wenn ich es nicht hinbekomme würdest du es dir mal anschauen via Teams, da kann ich dir mein bildschirm teilen

**Comment by jpgorganizer** [comment]
ich glaub nicht, dass dieser Fehler an dir liegt. Wenn über die API keine Daten zurückkommen, dann kannst werder du noch ich was machen. 
Der Login geht ja, also sollte es auch funktionieren. Die beiden APIs hast du aber schon verknüpft?

**Comment by Marshammer** [comment]
Ich denke ich hab ein Fehler bei den APIs hab beide
<img width="678" alt="Bildschirmfoto 2020-05-30 um 21 58 30" src="https://user-images.githubusercontent.com/66111826/83338071-db9ad780-a2c0-11ea-9d79-5b7bc90918e3.png">

**Comment by jpgorganizer** [comment]
das sieht gut aus

**Comment by Marshammer** [comment]
also jetzt ist er Grün zeigt leider nix an und melden im Log
<img width="700" alt="Bildschirmfoto 2020-05-31 um 12 42 15" src="https://user-images.githubusercontent.com/66111826/83350430-5fde7080-a33c-11ea-8a12-54d50fb8d63b.png">

**Comment by jpgorganizer** [comment]
kommen sonst noch log meldungen?
gestoppt und frisch gestartet?

**Comment by Marshammer** [comment]
nein nur diese alleine

**Comment by jpgorganizer** [comment]
nur diese eine Zeile und sonst nichts? auch wenn du frisch startest?

**Comment by Marshammer** [comment]
Dann kommt wieder no Data.

**Comment by jpgorganizer** [comment]
na dann, hätte mich auch gewundert
Python3 Scripte kannst du ja nicht laufen lassen, also können wir zunächst mal nicht weiter suchen. Es gibt noch einen anderen User mit dem gleichen Problem, evtl. finden wir da eine Ursache.

Ich hab gerade gesehen, dass in einem anderen Forum der gleiche Fehler gemeldeet wird, dort hat das aber nichts mit iobroker zu tun.
Mal sehen.

**Comment by jpgorganizer** [comment]
see https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/423

**Comment by jpgorganizer** [comment]
@Marshammer 

see
https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/423

**Comment by jpgorganizer** [comment]
@Marshammer 

bitte testen und Hinweise hier beachten
https://forum.iobroker.net/post/444008

**Comment by jpgorganizer** [comment]
super, dann schließe ich hier auch
