### ISSUE TITLE
Service  SERVICE_VALVE - PAUSE Command

### ISSUE THREAD

**Issue by jroegner** [jpgorganizer/ioBroker.smartgarden#14]
Zum steuern der Ventile wird der Wert in "duration_value" gesetzt. Laut Beschreibung kann mit "PAUSE" der Zeitplan für eine bestimmte Zeit ausgesetzt werden (z.B. Regen etc.)

"to skip automatic operation until specified time, the currently active operation might or might not be cancelled (depends on device model) use string PAUSE"

Der String "PAUSE" alleine reicht hier aber nicht und hat keine Auswirkung. Irgendwo müsste noch die Dauer der Pause spezifiziert werden? Das ist aktuell nicht möglich?
![VALVE](https://user-images.githubusercontent.com/66469064/83863615-db1c9980-a723-11ea-8696-7641a4b20034.jpg)

**Comment by jpgorganizer** [comment]
richtig, PAUSE wird eigentlich auch nicht unterstützt - so wie bei der POWER_SOCKET auch. Ist mir aus Versehen in die Doku gerutscht. 
Vielleicht überlege ich mir was. Mal sehen.

**Comment by jpgorganizer** [comment]
Bitte teste eine Spezialversion einer Datei `api.js`. 
https://github.com/jpgorganizer/test4smartgarden/tree/master/lib

Dort liegt auch  ein README mit Infos

**Comment by jroegner** [comment]
Hi,
funktioniert nun perfekt! Super!
Vielen Dank!
Wenn jetzt noch beim Mower unter "activity_control_i" der Wert "start_resume_schedule" möglich ist, kann man den Garten bei Regen perfekt vor Bewässerung und Mähnen schützen und nach gewisser Zeit die Zeitpläne wieder aktivieren...

**Comment by jpgorganizer** [comment]
> funktioniert nun perfekt! Super!

danke für die Rückmeldung

> Wenn jetzt noch beim Mower unter "activity_control_i" der Wert "start_resume_schedule" möglich ist,

und was würde dieser Wert machen? Erklär doch mal

**Comment by jroegner** [comment]
Der Wert wird benötigt, wenn der Mäher der park_unit_further_notice bis auf Widerruf geparkt wurde, um wieder in den regulären Zeitplan gebracht zu werden.

Aktuell löse ich das noch über blockly mit meinem Regenmesser und dem Garden Adapter:
![image](https://user-images.githubusercontent.com/66469064/83970050-b23b0680-a8d3-11ea-8f4c-df7d818bfea9.png)

**Comment by jpgorganizer** [comment]
na da verwechselst du jetzt aber die Adapter. das ist vom anderen (ich sag mal alten Adapter auf nicht freigegebener Schnittstelle). Das kannst du nicht übertragen. 

Ich würde es mal mit `START_DONT_OVERRIDE` versuchen. Vmtl. genau das was du suchst. Ansonsten kann ich dir da nicht weiterhelfen, da es mehr nicht gibt von Gardena.

**Comment by jroegner** [comment]
Ja ich weiß, das ist der andere Adapter, den ich eigentlich nicht mehr einsetzen will, wenn ich alles mit Smartgarden abbilden kann.

Ich versuche das mal mit START_DONT_OVERRIDE, super vielen Dank.
