### ISSUE TITLE
Question - SERVICE_SENSOR controlling options

### ISSUE THREAD

**Issue by basic80** [jpgorganizer/ioBroker.smartgarden#15]
Although the documentation states that there are no controlling options for SERVICE_SENSOR, would it be possible to trigger an update for the values? 

The values, espescially for soil humidity, are only update every now and then. Under certain circumstances, it would be good to manually initate an update to make sure, that the values aren't out of date.

Since this is possible from within the smartphone app, I guess the Gardena API is supporting it as well.

**Comment by jpgorganizer** [comment]
Hi, I'm sorry, but this is not possible.

There exist two APIs for access to the Gardena devices: 

- one public API and 
- one internal API

This adapter uses the public API and the Gardena App uses the internal API. So it is possible that you have different possibilities between the Gardena App and this adapter.
