### ISSUE TITLE
GET_LOCATIONS

### ISSUE THREAD

**Issue by ppb1308** [jpgorganizer/ioBroker.smartgarden#16]
Hello,

i have checked using the API on API-Website and it works well with my application key.

I installed the adapter and entered my mail-address, ma password and the application key and set log level to highest.
I have an Water Control running.
When i start the instance i unfortunately get no data, see log.

Do you have any idea, why this /LOCATIONS does not work in the adapter?

Thank you in advance,
Peter

Log ioBroker when starting instance:
smartgarden.0 | 2020-07-16 09:32:23.317 | info | (17014) 3/ ---> State change by device
-- | -- | -- | --
smartgarden.0 | 2020-07-16 09:32:23.317 | info | (17014) 3/ state smartgarden.0.info.connection changed: false (ack = true)
smartgarden.0 | 2020-07-16 09:32:23.315 | error | (17014) Error: getlocations: no data
smartgarden.0 | 2020-07-16 09:32:23.119 | info | (17014) 3/ ---> State change by device
smartgarden.0 | 2020-07-16 09:32:23.119 | info | (17014) 3/ state smartgarden.0.info.connection changed: true (ack = true)
smartgarden.0 | 2020-07-16 09:32:23.118 | info | (17014) 3/ ---> State change by device
smartgarden.0 | 2020-07-16 09:32:23.118 | info | (17014) 3/ state smartgarden.0.info.connection changed: true (ack = true)
smartgarden.0 | 2020-07-16 09:32:23.113 | info | (17014) 3/ get_locations ...
smartgarden.0 | 2020-07-16 09:32:23.113 | info | (17014) 3/ connected ... auth_data=eyJhXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
smartgarden.0 | 2020-07-16 09:32:23.112 | info | (17014) 3/ sgSetState: info.connection value=true ack=true
smartgarden.0 | 2020-07-16 09:32:23.112 | info | (17014) 3/ Connection: successful: response.statusCode / statusMessage=200 / OK
smartgarden.0 | 2020-07-16 09:32:22.817 | info | (17014) 3/ ---> Command should be sent to device
smartgarden.0 | 2020-07-16 09:32:22.817 | info | (17014) 3/ state smartgarden.0.testVariable changed: true (ack = false)
smartgarden.0 | 2020-07-16 09:32:22.817 | info | (17014) 3/ ---> State change by device
smartgarden.0 | 2020-07-16 09:32:22.817 | info | (17014) 3/ state smartgarden.0.info.revision changed: Main: 2160 / API: 2167 (ack = true)
smartgarden.0 | 2020-07-16 09:32:22.817 | info | (17014) 3/ ---> State change by device
smartgarden.0 | 2020-07-16 09:32:22.817 | info | (17014) 3/ state smartgarden.0.info.connection changed: false (ack = true)
smartgarden.0 | 2020-07-16 09:32:22.789 | info | (17014) 3/ Gardena Smart System Service hosts at: smart_host: https://api.smart.gardena.dev authentication_host: https://api.authentication.husqvarnagroup.dev
smartgarden.0 | 2020-07-16 09:32:22.788 | info | (17014) 3/ sgSetState: info.revision value=Main: 2160 / API: 2167 ack=true
smartgarden.0 | 2020-07-16 09:32:22.773 | info | (17014) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.smartgarden, node: v10.21.0, js-controller: 3.1.4
smartgarden.0 | 2020-07-16 09:32:20.438 | info | (15390) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
smartgarden.0 | 2020-07-16 09:32:20.438 | info | (15390) terminating
smartgarden.0 | 2020-07-16 09:32:20.438 | info | (15390) 3/ cleaned everything up...
smartgarden.0 | 2020-07-16 09:32:20.437 | info | (15390) Got terminate signal TERMINATE_YOURSELF

**Comment by ppb1308** [comment]
Hello,

problem solved, deleted api key and created new, restartet instance, now it works.
Thank you for your work!

best regards,
Peter

**Comment by jpgorganizer** [comment]
yes that's the solution
I assume that your "old" API key was created some weeks ago and not this week. Right?
