### ISSUE TITLE
Zeitplan in Adapter übernehmen

### ISSUE THREAD

**Issue by audi1503** [jpgorganizer/ioBroker.smartgarden#17]
hallo ist es möglich den Zeitplan den man per Gardena Smart App einstellt mit in den Objekten anzeigen zu lassen? dann könnte man per VIS einen eigenen Zeitplan erstellen. habe gesehen das es beim Worx Adapter möglich is.

**Comment by StrathCole** [comment]
Nein, die Gardena-APi liefert die Infos (noch) nicht.

**Comment by audi1503** [comment]
Schade, aber ok . Setze den issue dann auf Closed.

**Comment by jpgorganizer** [comment]
siehe https://github.com/jpgorganizer/ioBroker.smartgarden#Wishes-for-data-points
