### ISSUE TITLE
Update stable version in repo from 1.0.1 to 1.0.2

### ISSUE THREAD

**Issue by GermanBluefox** [jpgorganizer/ioBroker.smartgarden#19]
# Think about update stable version to 1.0.2
**Version**: stable=**1.0.1** (43 days old) => latest=**1.0.2** (30 days old)
**Installs**: stable=**234** (54.8%), latest=**113** (26.46%), total=**427**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1303)

**Comment by jpgorganizer** [comment]
just released v1.0.3. 
If feedback will be positive, then update to stable for 1.0.3 planned

**Comment by jpgorganizer** [comment]
@GermanBluefox 
you write 


> **Installs**: stable=**234** (54.8%), latest=**113** (26.46%), total=**427**

Where do I find this figures?

**Comment by jpgorganizer** [comment]
v1.0.3 to stable; PR created

**Comment by jpgorganizer** [comment]
@GermanBluefox 
where can I find such info's? You've written those numbers a few months ago, but I would like to fetch those numbers regularly.

> **Version**: stable=**1.0.1** (43 days old) => latest=**1.0.2** (30 days old)
> **Installs**: stable=**234** (54.8%), latest=**113** (26.46%), total=**427**

Thanks in advance
jpgorganizer
