### ISSUE TITLE
State für Error-Code anlegen

### ISSUE THREAD

**Issue by StrathCole** [jpgorganizer/ioBroker.smartgarden#2]
Der State `lastErrorCode_value` existiert scheinbar nur, wenn er das erste Mal von der API gesendet wurde. Vielleicht kannst du den vorab schon anlegen, damit er von anderen Skripten "subscribed" werden kann, auch wenn noch kein Fehler aufgetreten ist.
Ggf. trifft das auch für andere States zu, das kann ich aber mangels genauer Kenntnis der Api nicht sagen.

**Comment by jpgorganizer** [comment]
Das ist richtig, States werden nur angelegt, wenn sie vom Gardena Webservice übertragen werden. Eigentlich habe ich erwartet, dass alles States bei der Initialisierung zumindest einmalig übertragen werden, damit der Client die vollständige Abbildung des Serverzustandes besitzt. 

Mir ist das bisher nicht aufgefallen, dass dem nicht so ist. Ist das sonst noch jemandem aufgefallen?

**Comment by StrathCole** [comment]
Laut Definition der API ist es so, dass **nicht** alle States zu Beginn übergeben werden. Siehe hier:
https://developer.1689.cloud/apis/GARDENA+smart+system+API#/readme im Abschnitt "Rules of events processing". Dort sieht man, dass beim PATCH event (2. Box) eine Eigenschaft übergeben wird, die vorher nicht existierte.

**Comment by jpgorganizer** [comment]
wird mit v0.4.0 kommen - Version ist im internen Test, kommt morgen oder übermorgen
