### ISSUE TITLE
Werte Aktualisieren von Sensoren

### ISSUE THREAD

**Issue by Scotty-89** [jpgorganizer/ioBroker.smartgarden#20]
Hallo zusammen,

eine Frage ... gibt es die Möglichkeit das man ein Update der Sensorwerte Triggern kann ?
ich habe bislang einen veralteten Adapter (Gardena Smart System) genutzt und da ging so etwas..
Würde ihn aber gern einstellen und Komplett auf diesen hier umsteigen da er aktueller ist ;) 

Vielen Dank schonmal.

**Comment by jpgorganizer** [comment]
Hi, nein, das ist weder möglich noch notwendig.
Wenn sich Werte ändern, dann werden diese automatisch aktualisiert.

VG jpgorganizer
