### ISSUE TITLE
Json Probleme 

### ISSUE THREAD

**Issue by fresenbruch** [jpgorganizer/ioBroker.smartgarden#22]
Seit gestern meldet der smartgarden-Adapter den foglenden Fehler:

smartgarden.0 | 2020-10-24 11:37:26.211 | error | at endReadableNT (_stream_readable.js:1145:12)
-- | -- | -- | --
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at IncomingMessage.emit (events.js:203:15)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at Object.onceWrapper (events.js:286:20)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at Request.emit (events.js:198:13)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at Request.emit (events.js:198:13)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.smartgarden/lib/api.js:2830:29)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | at JSON.parse (<anonymous>)
smartgarden.0 | 2020-10-24 11:37:26.211 | error | (3901) SyntaxError: Unexpected end of JSON input
smartgarden.0 | 2020-10-24 11:37:26.209 | error | (3901) uncaught exception: Unexpected end of JSON input
Den API-Key habe ich heute verifiziert.
DIe Ampel für den Adapter steht auf rot.

Was ist zu tun?

**Comment by jpgorganizer** [comment]
da kannst du aktuell nichts dagegen tun. Es gibt auf Gardena-Seite ein Problem. siehe [https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/546](https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/546)ff

**Comment by jpgorganizer** [comment]
https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/567
