### ISSUE TITLE
Get Location error 

### ISSUE THREAD

**Issue by DocLonAix** [jpgorganizer/ioBroker.smartgarden#23]
Since three days I get the following error in ioBroker. 

(18138) Error: getlocations: no data
--

I didn’t change anything and it was stable for months now.

**Comment by jpgorganizer** [comment]
please see [https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/546](https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/546)ff

**Comment by jpgorganizer** [comment]
https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/567
