### ISSUE TITLE
Verbindung zu Gardena aber Unexpected end of JSON input at JSON.parse

### ISSUE THREAD

**Issue by OberfragGER** [jpgorganizer/ioBroker.smartgarden#24]
Neuerdings geht der Adapter leider auf gelb bzw. rot.
Doe Verbindung zu Gardena steht/ ist vorhanden aber folgende Fehler tauchen im Log auf:

`

smartgarden.0 | 2020-10-25 18:32:33.965 | info | (15834) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
smartgarden.0 | 2020-10-25 18:32:33.964 | info | (15834) terminating
smartgarden.0 | 2020-10-25 18:32:33.919 | error | (15834) SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at Request._callback (/opt/iobroker/node_modules/iobroker.smartgarden/lib/api.js:2830:29) at Request.self.call
smartgarden.0 | 2020-10-25 18:32:33.917 | error | (15834) uncaught exception: Unexpected end of JSON input

smartgarden.0 | 2020-10-25 18:32:01.331 | info | (15243) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
smartgarden.0 | 2020-10-25 18:32:01.329 | info | (15243) terminating
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at endReadableNT (_stream_readable.js:1223:12)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at IncomingMessage.emit (events.js:326:22)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at Object.onceWrapper (events.js:420:28)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at Request.emit (events.js:314:20)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at Request.emit (events.js:314:20)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.smartgarden/lib/api.js:2830:29)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | at JSON.parse (<anonymous>)
smartgarden.0 | 2020-10-25 18:32:01.284 | error | (15243) SyntaxError: Unexpected end of JSON input
smartgarden.0 | 2020-10-25 18:32:01.280 | error | (15243) uncaught exception: Unexpected end of JSON input
smartgarden.0 | 2020-10-25 18:32:00.718 | info | (15243) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.smartgarden, node: v12.19.0, js-controller: 3.1.6

`

**Comment by jpgorganizer** [comment]
siehe #22 und #23

**Comment by jpgorganizer** [comment]
https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/567
