### ISSUE TITLE
Mäher Manuell los schicken

### ISSUE THREAD

**Issue by OlfrygtACAB** [jpgorganizer/ioBroker.smartgarden#25]
moin moin,
erstmal super arbeit, was den adapter angeht!

gibt es eine möglichkeit, den datenpunkt activity_control_i mit einem befehl zu beschreiben das der Mäher sofort losfährt bzw. zurück fährt ohne das er auf den zeitplan von gardena achtet

**Comment by jpgorganizer** [comment]
hi,
im readme stehen die Möglichkeiten. Aus meiner Sicht lassen sich deine Anforderungen damit abdecken.

https://github.com/jpgorganizer/ioBroker.smartgarden#for-service_mower

Beim Losfahren muss aber der Akku voll sein - zumindest mein Mäher fährt sonst nicht los.

**Comment by OlfrygtACAB** [comment]
> hi,
> im readme stehen die Möglichkeiten. Aus meiner Sicht lassen sich deine Anforderungen damit abdecken.
> 
> https://github.com/jpgorganizer/ioBroker.smartgarden#for-service_mower
> 
> Beim Losfahren muss aber der Akku voll sein - zumindest mein Mäher fährt sonst nicht los.

Ok, das mit dem Akku hatte ich nicht bedacht, da er nichts getan hat, bin davon ausgegangen das er bei Start nur wieder nach Zeitplan arbeitet.
