### ISSUE TITLE
Question - SmartSensor

### ISSUE THREAD

**Issue by Z18Aplha** [jpgorganizer/ioBroker.smartgarden#26]
First of all: Thank you for this adapter. So handy and usefull and even a nice documentation! Well done.

I plan to buy the new [SmartSensor](https://www.amazon.de/GARDENA-smart-Sensor-Bodentemperatur-Bew%C3%A4sserungssteuerung/dp/B08LNQGB99/ref=sr_1_1_sspa?adgrpid=73853780071&dchild=1&gclid=Cj0KCQjwgtWDBhDZARIsADEKwgOQcpk_4wt3ap4t7Z8pt92U2m3aEhWmXLOsLf7ci1sjwQ_pTG_RWTkaAtAzEALw_wcB&hvadid=353054996364&hvdev=c&hvlocphy=9042974&hvnetw=g&hvqmt=e&hvrand=2177775771218449873&hvtargid=kwd-510786271352&hydadcr=18403_1794502&keywords=smart+sensor+gardena&qid=1618333710&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzRDM0T0xXNlc3VEMzJmVuY3J5cHRlZElkPUEwNDQ1NzU2MU9DU0FaQkdQMTFYRCZlbmNyeXB0ZWRBZElkPUEwNzA3MDcyNDVFTkpXREVXN0RUJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==) to make my sprinkler system even more smart.

I read in #15 the values are pushed in random intervals by the sensor. For my implentation this should be no problem. It depends on the interval range. So the question:
```
How many value updates the sensor sends to the adapter per day (mean)?
```

**Comment by jpgorganizer** [comment]
Hi @Z18Aplha, 
this smart sensor is a new variant of the sensor.. But I don't have none of these sensors. So I cannot answer your question. 
Unfortunately, the  API (or docu) from Gardena does not document an update interval for values. And for the sensor it is not possible to request values. There is no API command available.

There was a question in the [forum (in German language)](https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/615) a few days ago that the sensor always shows the same value for the battery. Maybe you can ask there, maybe someone can answer your question there.

**Comment by Z18Aplha** [comment]
Thanks for your fast reply!
This [answer](https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/619) says the value is updated every hour. That would be great. I bought the sensor and if its not working as expected with this adapter i come back and report.

**Comment by jpgorganizer** [comment]
> This [answer](https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/619) says the value is updated every hour.

where do you read this? I cannot see that.  :-(

**Comment by Z18Aplha** [comment]
The answer is from 
12. Apr. 2021, 13:15
