### ISSUE TITLE
Manuelles Mähen startet Zeitplan

### ISSUE THREAD

**Issue by Glemp** [jpgorganizer/ioBroker.smartgarden#27]
An dieser Stelle erstmal vielen Dank für den Adapter

Mir ist ein Problem aufgefallen: 

Hat man den Zeitplan deaktiviert und startet den Mäher manuell per setzen von activity_control_i wird der Zeitplan aktiviert. Das passiert allerdings nur, wenn man den manuellen Start in einem Zeitfenster aktiviert, zu dem es einen Zeitplan gibt. Startet man den Mäher manuell außerhalb dieses Zeitfensters, bleibt auch der Zeitplan deaktiviert.

Führt man einen manuellen Start über die App aus, bleibt der Zeitplan immer deaktiviert.

Ist das ein Fehler auf meiner Seite, im Adapter oder in der API?

**Comment by jpgorganizer** [comment]
> Hat man den Zeitplan deaktiviert und startet den Mäher manuell per setzen von activity_control_i wird der Zeitplan aktiviert.
 
wie aktivierst du? Welchen Wert setzt du?


> Das passiert allerdings nur, wenn man den manuellen Start in einem Zeitfenster aktiviert, zu dem es einen Zeitplan gibt. Startet man den Mäher manuell außerhalb dieses Zeitfensters, bleibt auch der Zeitplan deaktiviert.

interessante Abhängigkeit. 


> Ist das ein Fehler auf meiner Seite, im Adapter oder in der API?
Der Adapter macht eigentlich nichts. Er reicht die Werte, die man übergibt "nur" durch. Somit tippe ich auf eine Änderung in der API/Webservice.



> Führt man einen manuellen Start über die App aus, bleibt der Zeitplan immer deaktiviert.
Ich hatte meinen Mäher nur ganz kurz am Laufen dieses Jahr und mir war auch aufgefallen, dass es sich irgendwie seltsam verhält, nur meine Beobachtung war, dass der Zeitplan immer aktiviert wurde

Sieht für mich danach aus, dass man das Verhalten mit den Randbedingungen mal genau beobachten muss.

**Comment by Glemp** [comment]
Ich hab heute nochmal ganz genau getestet und kann hier Entwarnung geben. Auch über die App wird der Zeitplan aktiviert, wenn man den Mäher manuell starten.
Es bleibt aber dabei, dass es in Abhängigkeit der Zeitplaneinträge passiert. Sehr merkwürdig. Ich werde es mal bei Gardena melden. Mal abwarten, was die dazu sagen. Ich bin der Meinung, dass es in der letzten Saison anders war.

Also nichts für Ungut und vielen Dank für die schnelle Rückmeldung.

**Comment by jpgorganizer** [comment]
Danke für dein Feedback. 
Somit kein Problem im Adapter. Ich schließe das issue, ggfs. machen wir ein neues auf,falls erforderlich
