### ISSUE TITLE
Objekte mit passendem Typ und Rolle anlegen

### ISSUE THREAD

**Issue by StrathCole** [jpgorganizer/ioBroker.smartgarden#3]
Aktuell sind alle Objekte vom Typ "State" und haben den Datentyp "String" mit Rolle "Text".

Dies sollte geändert werden, sodass die Objekte dem Datenschema von ioBroker folgen.

Beispiele: `rfLinkLevel_value` hätte den Datentyp "number" und die Rolle "value". `rfLinkLevel_timestamp` hätte den Datentyp "number" und die Rolle "date" (Unix Timestamp).

Siehe hier: https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md
und hier: https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md

Zudem sollen nur echte "States" den Objekttyp "state" haben. DEVICE sollte den Objekttyp "device" haben, es darf aber kein Stateinhalt gesetzt werden (aktuell "DEVICE").
Die Punkte SERVICE_COMMON / SERVICE_XXXX sollten vom Objekttyp "channel" sein und ebenfalls keine Werte im State haben.

Der Datenpunkt `activity_value_i` hat den Wert "MOWING" oder "NOT_MOWING". In meinen Augen wäre hier ein State vom Typ `boolean` mit der Rolle `indicator` besser. Das könnte man dann auch in der Visualisierung gut verwenden.

**Comment by jpgorganizer** [comment]
> Zudem sollen nur echte "States" den Objekttyp "state" haben. 

hört sich sinnvoll an. Schaue ich mir an und wird ggfs. angepasst

> Der Datenpunkt activity_value_i hat den Wert "MOWING" oder "NOT_MOWING". In meinen Augen wäre hier ein State vom Typ boolean mit der Rolle indicator besser. 


es gibt max. fünf Datenpunkte (und die nicht bei jedem Gardena device), die man auch als nicht TEXT (string) abbilden könnte:

- rfLinkLevelValue (integer)
- stop_all_valves_i (boolean) (command bei VALVE_SET) 
- activity_value_i (boolean) (nur MOWER)
- durationHoursValue (integer) (nur MOWER)
- batteryLevelValue (integer)  (nur bei Geräten mit Batterie (MOWER und SENSOR (der hat doch eine Batterie ???))

Der Service von Gardena überträgt alles als Text und keine Information um welchen Datentyp es sich handelt. Dies müsste als Wissen im Adapter vorgehalten werden. Bei Erweiterungen der Gardena Schnittstelle durch Gardena wären dann Anpassungen erforderlich.

Die Datenpunkte des Adapters sind eigentlich fast alles Werte, die nur für eine Anzeige gedacht sind und nicht für weitergehende Berechnungen. Wie sinnvoll wäre ein anderer Datentyp für diese Werte wirklich?

**Comment by StrathCole** [comment]
Es ist grundsätzlich so, dass in ioBroker die States den passenden Typ und die passende Rolle haben sollen. Besonders für Widgets in der Vis und solche Dinge ist der Typ wichtig. Es wäre also durchaus sinnvoll, im Adapter eine Liste von States zu pflegen und den entsprechenden Typ zu hinterlegen. Selbst bei den States, die wirklich als Text gespeichert werden, wäre zumindest die passende Rolle nicht verkehrt, wie bspw. `info.name` oder `info.status`.

Beim Ladezustand (`batteryLevelValue`) ist zudem sogar noch eine `unit` zu setzen (%).

Ich habe das im Tahoma Adapter auch so machen müssen:  
Siehe https://github.com/StrathCole/ioBroker.tahoma/blob/master/lib/tahoma.js#L204 und folgende Zeilen.

**Comment by jpgorganizer** [comment]
wird mit v0.4.0 kommen - Version ist im internen Test, kommt morgen oder übermorgen
