### ISSUE TITLE
ERR! syscall accessnpm ERR! path /opt/iobroker/node_modules/canvasnpm ERR! errno -40

### ISSUE THREAD

**Issue by Planetus88** [jpgorganizer/ioBroker.smartgarden#31]
Hallo,

wollte gerade auf die neue Version Updaten, nun bekomme ich diesen Fehler:

> $ ./iobroker upgrade smartgarden
Update smartgarden from @1.0.4 to @1.0.5
NPM version: 6.14.12
npm install iobroker.smartgarden@1.0.5 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ELOOP
npm ERR! syscall accessnpm ERR! path /opt/iobroker/node_modules/canvasnpm ERR! errno -40
npm ERR! ELOOP: too many symbolic links encountered, access '/opt/iobroker/node_modules/canvas'
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-05-21T09_44_04_995Z-debug.log
ERROR: host.iobroker-master Cannot install iobroker.smartgarden@1.0.5: 216
ERROR: process exited with code 25

2021-05-21T09_44_04_995Z-debug.log:

> 58 silly saveTree ├── semver@5.7.1
58 silly saveTree └── yargs@7.1.1
59 warn @date-io/date-fns@1.3.13 requires a peer of date-fns@^2.0.0 but none is installed. You must install peer dependencies yourself.
60 warn @material-ui/pickers@3.3.10 requires a peer of @material-ui/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
61 warn @material-ui/pickers@3.3.10 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
62 warn @material-ui/pickers@3.3.10 requires a peer of react-dom@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yours$
63 warn react-transition-group@4.4.1 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself.
64 warn react-transition-group@4.4.1 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself.
65 warn rifm@0.7.0 requires a peer of react@>=16.8 but none is installed. You must install peer dependencies yourself.
66 verbose stack Error: ELOOP: too many symbolic links encountered, access '/opt/iobroker/node_modules/canvas'
67 verbose cwd /opt/iobroker
68 verbose Linux 4.19.0-14-amd64
69 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.smartgarden@1.0.5" "--loglevel" "error" "--prefix" "/opt/iobroker"
70 verbose node v12.22.1
71 verbose npm  v6.14.12
72 error code ELOOP
73 error syscall access
74 error path /opt/iobroker/node_modules/canvas
75 error errno -40
76 error ELOOP: too many symbolic links encountered, access '/opt/iobroker/node_modules/canvas'
77 verbose exit [ -40, true ]

Kann mir jemand einen Tipp geben was ich machen muss? :-)
Gruß
Tom

**Comment by jpgorganizer** [comment]
das ist ein npm Problem mit deiner iobroker Installation. 
frag mal im Forum .... bzw. suche dort. Es gibt mind. einen solchen Thread dort: https://forum.iobroker.net/topic/34945/too-many-symbolic-links-encountered-access-canvas

das ist kein Problem des Adapters, deshalb schließe ich hier
