### ISSUE TITLE
The adapter is yellow 

### ISSUE THREAD

**Issue by mcbirne** [jpgorganizer/ioBroker.smartgarden#32]
Hello,
Since 1 or 2 days the adapter is yellow. If I restart it I get the massage "(32233) Error: request returned 401 Unauthorized " 

Regards
Hartmut

**Comment by hobili** [comment]
Hi, 

same Problem here!

br
Holger

**Comment by jpgorganizer** [comment]
see https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/699
