### ISSUE TITLE
No connection to Gardena Cloud

### ISSUE THREAD

**Issue by MiRen76** [jpgorganizer/ioBroker.smartgarden#33]
Since a few days (4 or 5) the adapter is not able to connect to the Garden cloud giving the following error in the log:
(37362) Error: request returned 403 Forbidden

Does anybody has the same behaviour and know how to solve?

**Comment by Didi1205** [comment]
see https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/699

**Comment by Didi1205** [comment]
Are the APIs  (Application, Husqvarna Account) conected?

![image](https://user-images.githubusercontent.com/61842614/125103325-87c20b00-e0dc-11eb-86ec-8931eda9a801.png)

**Comment by MiRen76** [comment]
OK, workaround with API key renewal solved the issue, THX

**Comment by MiRen76** [comment]
I close this issue
