### ISSUE TITLE
3027) Error: request returned 429 

### ISSUE THREAD

**Issue by lolax80** [jpgorganizer/ioBroker.smartgarden#34]
Hallo zusammen, ich muss ca 2 mal im Monat den API Code auf der Gardena Webseite neu erstellen lassen und dann im Adapter eintragen, damit es wieder geht, ansonsten kommt der obige Fehler.

Mit freundlichen Grüßen
Alexander

**Comment by jpgorganizer** [comment]
this is a problem of the Gardena Cloud system. It's not possible for the adapter to solve that.

see https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/699

and please test in case of an error with the testscript mentioned in one of the following posts
