### ISSUE TITLE
WARN: batteryLevel_value has been written without ack-flag

### ISSUE THREAD

**Issue by RP70DP** [jpgorganizer/ioBroker.smartgarden#38]
`2021-09-17 19:40:04.071  - [33mwarn[39m: socketio.0 (15241) Read-only state "smartgarden.0.LOCATION_XXX.DEVICE_XXX.SERVICE_COMMON_XXX.batteryLevel_value" has been written without ack-flag with value "9"`

It's a smart water control.

**Comment by jpgorganizer** [comment]
@RP70DP
does this also happen for batteryLevel_timestamp?

**Comment by RP70DP** [comment]
I can't remember. At the Moment the device is in hibernation mode, because it's winter.
I will check in the spring.

**Comment by jpgorganizer** [comment]
can you give the names of all data points (SERVICE_COMMON  and SERVICE_VALVE) for your water control? Typically I don't like screenshots, but maybe here that would be the best solution :-)

**Comment by RP70DP** [comment]
![tempsnip](https://user-images.githubusercontent.com/62850183/165752340-d6629e62-7c43-4174-a182-905e1933493a.png)

**Comment by jpgorganizer** [comment]
Hi, this are data points just for a water control? do you have a smart irrigation control too?  I'm wondering about the SERVICE_VALVE_SET.

**Comment by RP70DP** [comment]
Yes, only Water Control. No Irrigation Control existing.

Okay, will do that at the next opportunity.

**Comment by jpgorganizer** [comment]
please open new issue if error still exists
