### ISSUE TITLE
States dürfen nicht "writeable" sein

### ISSUE THREAD

**Issue by StrathCole** [jpgorganizer/ioBroker.smartgarden#4]
Mit Commit https://github.com/jpgorganizer/ioBroker.smartgarden/commit/17d8f68a255a0f4c9f15c8b9d14cce8255d7ab78 wurden alle States als `write: true` angelegt.

`write: true` ist nur für States gedacht, die vom Benutzer verändert werden sollen, also Kommandos auslösen. Siehe https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md (write-only, read-only oder read-write).

**Comment by StrathCole** [comment]
Related to #3

**Comment by jpgorganizer** [comment]
da ist klar, nur da @dslraser das Problem hatte, dass er gar keine States beschreiben konnte wurde das mal so geändert um zu sehen ob das was bewirkt bei ihm.

**Comment by jpgorganizer** [comment]
wird mit v0.4.0 kommen - Version ist im internen Test, kommt morgen oder übermorgen

**Comment by jpgorganizer** [comment]
wird mit v0.4.0 kommen - Version ist im internen Test, kommt morgen oder übermorgen
