### ISSUE TITLE
API V1

### ISSUE THREAD

**Issue by Drillo123** [jpgorganizer/ioBroker.smartgarden#42]
With the basic setting:
https://api.authentication.husqvarnagroup.dev and https://api.smart.gardena.dev
I get the error message:
smartgarden.0 2022-03-10 20:31:39.815 error Error: request returned 401 Unauthorized

I change the setting as shown in my Gardenaaccount to:
https://api.authentication.husqvarnagroup.dev/v1 and https://api.smart.gardena.dev/v1
I get the error message:
smartgarden.0 2022-03-10 20:37:53.689 error Error: request returned 403 Forbidden

So it no longer works with both variants. Am I doing something wrong? It used to work (last summer) but now I've noticed that it doesn't work anymore.

**Comment by jpgorganizer** [comment]
> With the basic setting:
> https://api.authentication.husqvarnagroup.dev and https://api.smart.gardena.dev
> I get the error message:

this are the correct addresses

Gardena interface is up an running, so I assume that the error is on your side. 

pls check your password and api key; perhaps create a new api key - this helped others
