### ISSUE TITLE
Adapter loses connection to service/device

### ISSUE THREAD

**Issue by MiRen76** [jpgorganizer/ioBroker.smartgarden#44]
The adapter basically works as desigend. But after a few hours of being connected it losses the connection to the service/device and traffic light turns yellow. Only a restart of the adapter will fix this issue. The debug log does not show any entries why loosing connection.

My configuration is as follows
Adapter version 1.0.5
JS-Controller: 4.0.23
NPM: 6.14.16

I already tried to set up a new instance with a new API. But the result was the same.
Does anybody has a clue?

**Comment by jpgorganizer** [comment]
see issue https://github.com/jpgorganizer/ioBroker.smartgarden/issues/43

new version gets released today
