### ISSUE TITLE
Batterylevel allways 99%

### ISSUE THREAD

**Issue by mcbirne** [jpgorganizer/ioBroker.smartgarden#46]
Hello,
the batterylevel is allways 99%.

**Comment by DizzelPopitzel** [comment]
Hi jpgorganizer,
same here. My observation is, that the whole SERVICE_COMMON section is not updated very often. I had battery LOW/7% today and it remains there after battery change now for hours. And rfLinkState remains ONLINE when batteries are remove. 
Is the update interval configurable anywhere?

**Comment by jpgorganizer** [comment]
Which de ice?
Please provide log with log level 3
Values get updated by Gardena server if there is a change. If not, then it's an issue of the Gardena Server and not of smart garden adapter.
let's check

**Comment by jpgorganizer** [comment]
Try to reproduce that where you mean that this is an error. Maybe you should wait until the battery level should change. 

Battery change is not a good scenario for searching an error. 

And no, I don't need the login procedure.

**Comment by DizzelPopitzel** [comment]
Here is my observation while log level 3:
- batteryLevel_value changes do not cause any Gardena-side events
- only regular pong appear
- updated values are passed to the adapter on any interaction with the device like pressing the open/close button
- if you do not interact you will get not updated value
So it's not an issue of the adapter.

Having this said the question comes up: What is the intension of SERVICE_COMMON.rfLinkState_value? It's always ONLINE. Under which condition will that value change?

**Comment by mcbirne** [comment]
I have an gardena smart city. That it the debug log
![image](https://user-images.githubusercontent.com/38691204/170210486-0259f7d7-ab8b-48e3-b532-6ad10f1e5167.png)

**Comment by jpgorganizer** [comment]
> Having this said the question comes up: What is the intension of SERVICE_COMMON.rfLinkState_value? It's always ONLINE. Under which condition will that value change?

This are question's to ask Gardena. The adapter just saving received  values.
I don't have access to devices with a battery like sensor or water control. Just my mower have a battery and the values are updated regularly.

**Comment by jpgorganizer** [comment]
@mcbirne 
Sorry his is helpless. Logs please just with level 3 and NOT as an image

And I couldn't find any error

**Comment by jpgorganizer** [comment]
do you have new infos to share? If not I will close issue on 01.06.22 as no more relevant.

**Comment by mcbirne** [comment]
No, I have no new information. Last time I check the battery level it was lower than 100‰ maybe it was a problem by gardena.

**Comment by jpgorganizer** [comment]
pls create new issue if error still exists
