### ISSUE TITLE
403 Forbidden - Adapter funktioniert nicht mehr seit 09.06.2022

### ISSUE THREAD

**Issue by jupzup** [jpgorganizer/ioBroker.smartgarden#47]
403 Forbidden - Adapter funktioniert nicht mehr seit 09.06.2022

Habe mich eben mal eingeloggt auf: https://developer.husqvarnagroup.cloud/ und meine Applications waren einfach nicht mehr vorhanden !!

Habe dann eine neue angelegt und den Token kann ich per Terminal auch holen. Was mir aber aufgefallen ist, dass man sich nicht mehr per Username & Passwort authentifizieren kann sondern nur noch mittels Application UND Secret Key.

Keine Ahnung ob das neu ist und hier etwas geändert wurde. Wenn ja dann muss sicher der Adapter hier entsprechend angepasst werden.

**Comment by hobili** [comment]
habe leider das gleiche Problem :-(

**Comment by yogiflop** [comment]
hier auch

**Comment by gaga191281** [comment]
+1

**Comment by hobili** [comment]
11 Uhr - schein ein Fehler vom Server gewesen zu sein, jetzt geht es gerade wieder!

**Comment by Schlumpel** [comment]
das oben beschriebene Problem hab ich auch. "Error occured:
smartgarden.0 (6111) Error: request returned 400 Bad Request"

**Comment by jpgorganizer** [comment]
next release v1.1.0 is planned for  2022/06/13

**Comment by Hamburger2022** [comment]
great - many Thanks @jpgorganizer

**Comment by Schroed99** [comment]
@jpgorganizer vielen Dank, habe mir extra wegen deiner Instanz einen Gardena Gateway gekauft :-)

**Comment by Schroed99** [comment]
> https://github.com/jpgorganizer/ioBroker.smartgarden/releases/tag/v2.0.0

Hey, ich habe die neue Version getestet. Die Stelle an der ich den Applikation Security Key eingeben muss, ist ausgeraut.
![image](https://user-images.githubusercontent.com/79341307/173378511-3ff9b614-aeb8-4ba7-86d8-d6a0c16d5fff.png)
Mach ich etwas falsch?

![image](https://user-images.githubusercontent.com/79341307/173378888-133d4e7a-7c0b-4189-b567-a87cd9dd6959.png)

Danke

**Comment by Schroed99** [comment]
> please delete username and password

Perfekt! Vielen Dank, hat funktioniert! 
![image](https://user-images.githubusercontent.com/79341307/173394874-7b913c19-5569-4432-b018-db14d4cbe920.png)

**Comment by Rette70** [comment]
Hallo,
bei mir funktioniert der Adapter auch nicht mehr.
habe es mit oder ohne Email versucht. Jetzt sogar den Adapter deinstalliert.
PLATTFORM : LINUX
BETRIEBSSYSTEM : LINUX
ARCHITEKTUR : ARM
CPUS : 4
GESCHWINDIGKEIT : 1500 MHZ
MODELL : ARMV7 PROZESSOR REV 3 (V7L)
ARBEITSSPEICHER : 3,7 GB
SYSTEM-BETRIEBSZEIT : 00:30:26
NODE.JS : V14.19.0
ZEIT : 1656085964149
TIMEOFFSET : -120
ADAPTER-ANZAHL : 421
NPM : 6.14.8
DATENTRÄGERGRÖSSE: 28,9 GB
FREIER FESTPLATTENSPEICHER : 9,7 GB
BETRIEBSZEIT : 00:30:04
AKTIVE INSTANZEN : 21
PFAD : /OPT/IOBROKER/
startInstance system.adapter.smartgarden.0 Adapterabhängigkeit auf keinem Host erfüllt: erforderlicher Adapter "admin" hat falsche Version. Installiert "5.3.1", erforderlich ">=5.3.2"!
Kann da jemand helfen? 

Gruß Mario

**Comment by bvol** [comment]
> Hallo, bei mir funktioniert der Adapter auch nicht mehr. habe es mit oder ohne Email versucht. Jetzt sogar den Adapter deinstalliert.

Email und PW löschen. API KEY und Secret eintragen - fertig.
