### ISSUE TITLE
LOG Error: request returned 403 Forbidden

### ISSUE THREAD

**Issue by sekinooo** [jpgorganizer/ioBroker.smartgarden#48]
I have requested API key, and entered my username (email adress) and password to adapter, but I have Error: request returned 403 Forbidden in my log and Can't connect to device or service. Can you please explain what is the issue? I changed auth url to https://api.authentication.husqvarnagroup.dev/v1 and base url to https://api.smart.gardena.dev/v1 . Password is correct. i have no Secret key  field as in your documentation, just user and password fields. Thank you!

**Comment by Hamburger2022** [comment]
Do you use already version 2 of the Adapter?
I installed it directly from github

**Comment by Hamburger2022** [comment]
You have to go to menu:
Adapter
Look for the github cat symbol (perhaps you have to activate expert mode in iobroker)

click on the cat symbol:
Choose the last tab (custom / „benutzerdefiniert“ )

put the url of the the github tag oder branch
Best

**Comment by sekinooo** [comment]
I tried but I'm stucked on installation screen for 10 minutes 
![iobroker](https://user-images.githubusercontent.com/57954363/173667109-c3ac434c-8e22-4b08-8edc-495b09b7b696.jpg)

**Comment by Hamburger2022** [comment]
It took a long time - I did it last night, this morning it worked

**Comment by jpgorganizer** [comment]
> ? I changed auth url to https://api.authentication.husqvarnagroup.dev/v1 and base url to https://api.smart.gardena.dev/v1 .

why do you use those adresses? why do you use `/v1`?

**Comment by jpgorganizer** [comment]
> It took a long time - I did it last night, this morning it worked

This is a topic of ioBroker and/or github .... nothing that an adapter can influence

**Comment by sekinooo** [comment]
it shows on https://developer.husqvarnagroup.cloud/apis/GARDENA+smart+system+API#/general
![Uploading husqa.png…]()

**Comment by sekinooo** [comment]
why iobroker is not updating to v 2.0 ?

**Comment by jpgorganizer** [comment]
works now
