### ISSUE TITLE
keine Bewässerung wenn gemäht wird

### ISSUE THREAD

**Issue by jpgorganizer** [jpgorganizer/ioBroker.smartgarden#5]
Es sollte verhindert werden, dass die Bewässerung läuft, solange der Mäher mäht. 

Sinnvoll weil der Mäher ggfs. gegen Versenkregner fährt und dabei Schäden am Regner wie auch am Mäher entstehen können.

Der Mäher hat Vorrang vor der Bewässerung, da er auch am Mäher selbst gestartet werden kann. Eine evtl. laufende Bewässerung wird dann abgebrochen.

Konfiguration pro Ventil erforderlich, da es Regnerkreise geben kann, die vom Mäher nicht beeinträchtigt sind.

**Comment by gfacek** [comment]
Ist das nicht eine Logic, die du selbst in iobroker scripten müsstest? Bzw. eigentlich müsste das eher ein Job von Gardena/Husqvarna sein.

**Comment by jpgorganizer** [comment]
richtig, das muss selbst entwickelt werden. Gardena könnte das auch machen, aber gibt es zumindest bisher nicht. Somit werde ich das bei Gelegenheit in Angriff nehmen, denn das ist für mich ein sinnvoll nutzbares Feature.

**Comment by jpgorganizer** [comment]
in 0.6.0 enthalten
