### ISSUE TITLE
Stop schedule of valve(s)

### ISSUE THREAD

**Issue by reutli** [jpgorganizer/ioBroker.smartgarden#50]
Hi,

I'm wonderung how to stop the schedule.

In documentation I've found:
"<h3 dir="auto"><a id="user-content-for-service_valve" class="anchor" aria-hidden="true" href="https://github.com/jpgorganizer/ioBroker.smartgarden#for-service_valve"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a>For SERVICE_VALVE</h3>
<h4 dir="auto"><a id="user-content-controlling-2" class="anchor" aria-hidden="true" href="https://github.com/jpgorganizer/ioBroker.smartgarden#controlling-2"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h4><h4 dir="auto">Controlling</h4>
<p dir="auto">To control the device use data point</p>
<ul dir="auto">
<li>
<p dir="auto"><code>duration_value</code></p>
<p dir="auto">Change this data point to start the valve.</p>
<ul dir="auto">
<li>
<p dir="auto">To start for a defined time  set the value to the value in seconds
(please use multiples of 60).</p>
<p dir="auto"><strong>Note:</strong> There are some limitations for the allowed values.
Please report if you see other limitations.</p>

device | limit
-- | --
GARDENA smart Irrigation Control | 5400 seconds (90 minutes)
GARDENA smart Pump | 36000 (10 hours)
GARDENA smart Water Control | 36000 (10 hours)

</li>
<li>
<p dir="auto">To cancel the current watering and continue with the schedule use string
<code>STOP_UNTIL_NEXT_TASK</code></p>
</li>
<li>
<p dir="auto">To skip automatic operation until specified time, the currently active
operation might or might not be cancelled (depends on device model) use string
<code>PAUSE_&lt;number_of_seconds&gt;</code>, e.g. <code>PAUSE_86400</code> to pause for 24 hours (please use multiples of 60)</p>
</li>
<li>
<p dir="auto">To restore automatic operation if it was paused use string <code>UNPAUSE</code></p>
</li>
</ul>
</li></ul>

So if I'd like to pause the schedule for let's say two days I'm supposed to add "PAUSE_172800" in "duration_value"?
This means this object "duration_value" is a string where I can put seconds & complete commands???

Second question: What to do to pause until further action? If I'm getting the documentation right the "Pause" command always should be used with seconds?

**Comment by jpgorganizer** [comment]
> object "duration_value" is a string

correct. 


> What to do to pause until further action?

not possible
