### ISSUE TITLE
Gardena Apps time schedules  doesn´t update data points of power socket

### ISSUE THREAD

**Issue by MyhubMRa** [jpgorganizer/ioBroker.smartgarden#51]
gardena power socket
The data points state_timestamp and activity_timestamp are not getting updated when my power sockets (19095-20) are switched by the time schedule funktion of my gardena app (version 3.4.1) 
this leads to wrong activity_value
Only if I turn the device off or on manually without (time schedules) they´re getting updated. 

Could you please check?

**Comment by jpgorganizer** [comment]
this is no bug of the adapter, it's related to the Gardena Cloud Server API

**Comment by Randy1st** [comment]
Thanks 
I’ll get in touch with Gardena
