### ISSUE TITLE
Sporadisch Error 429

### ISSUE THREAD

**Issue by LastPerfectTobi** [jpgorganizer/ioBroker.smartgarden#52]
Der Smartgarden Adapter erzeugt bei mir immer sporadisch folgende Errors, funktioniert aber sonst ohne Problem und wird auch alleine wieder grün. 

```
2022-07-25 15:06:37.842 - error: smartgarden.0 (5125) Error: request returned 429
2022-07-25 15:11:38.227 - error: smartgarden.0 (5125) Error: request returned 429
2022-07-25 15:16:38.636 - error: smartgarden.0 (5125) Error: request returned 429
2022-07-25 19:21:41.050 - error: smartgarden.0 (5125) Error: request returned 429
2022-07-25 19:26:41.479 - error: smartgarden.0 (5125) Error: request returned 429
2022-07-25 22:25:00.246 - error: smartgarden.0 (5125) Error: request returned 429
```

Adapter: 2.0.0
NPM: 8.11.0
Node.JS: 16.15.1

**Comment by reutli** [comment]
Das habe ich auch, die WebSocket Verbindung ist hinreichend instabil. Die Frage ist, ob das am Adapter oder an der API von Gardena liegt.

**Comment by x2on** [comment]
Bei mir das gleiche. Dachte es liegt am API Key, aber nach ein paar Tagen ging es bei mir erstmal wieder. Vielleicht das Rate Limit?

**Comment by reutli** [comment]
Ich habe gerade massiv Probleme Ventile über die API zu steuern. Ein bis zwei Ventile gehen noch, dann kommen 429er und bad request... wollte eigentlich auf die Steuerung mit iobroker umsteigen und alles da erledigen, ... aber so ist das nicht stabil nutzbar. Fraglich ob's auf Gardena Seite liegt (API) oder die etwas geändert haben in Sachen WebSocket und limits.

**Comment by sparrow1990** [comment]
Leider bekomme auch ich seit ein paar Tagen die Fehlermeldung 429. Der Mäher lässt sich nicht mehr ansprechen auch nicht wenn man die Instanz neu startet. 

Ggf. sieht hier jemand das Problemchen, welches ich nicht behoben bekomme.

Node.js 16.16.0
NPM 8.11.0
JS Contr. 4.0.23

Log:
`
smartgarden.0 | 2022-07-27 11:49:40.075 | info | 3/ on_pong: ++ pong'ed ++
-- | -- | -- | --
smartgarden.0 | 2022-07-27 11:47:10.073 | info | 3/ on_pong: ++ pong'ed ++
host.buanet-iobroker3 | 2022-07-27 11:46:40.860 | info | Updating repository "stable" under "http://download.iobroker.net/sources-dist.json"
smartgarden.0 | 2022-07-27 11:46:40.740 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.rfLinkState_value changed: ONLINE (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.737 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.modelType_value changed: GARDENA smart Mower (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.733 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.serial_value changed: 200709482 (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.729 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.rfLinkLevel_timestamp changed: 2022-07-27T08:44:47.765Z (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.725 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.rfLinkLevel_value changed: 100 (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.721 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.batteryState_timestamp changed: 2022-07-27T09:39:28.756Z (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.718 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.batteryState_value changed: OK (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.715 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.batteryLevel_timestamp changed: 2022-07-27T09:46:40.378Z (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.694 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.batteryLevel_value changed: 100 (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.686 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_COMMON_558f.name_value changed: Robert (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.683 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.operatingHours_value changed: 2308 (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.678 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_timestamp changed: 2022-07-27T09:39:28.756Z (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.675 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_value changed: PARKED_PARK_SELECTED (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.670 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_control_i changed: null (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.667 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_mowing_i changed: false (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.662 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.state_timestamp changed: 2022-07-27T09:39:28.756Z (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.655 | info | 3/ ---> State change by device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.state_value changed: OK (ack = true)
smartgarden.0 | 2022-07-27 11:46:40.646 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.rfLinkState_value value=ONLINE ack=true
smartgarden.0 | 2022-07-27 11:46:40.646 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.modelType_value value=GARDENA smart Mower ack=true
smartgarden.0 | 2022-07-27 11:46:40.646 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.serial_value value=200709482 ack=true
smartgarden.0 | 2022-07-27 11:46:40.645 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.rfLinkLevel_timestamp value=2022-07-27T08:44:47.765Z ack=true
smartgarden.0 | 2022-07-27 11:46:40.645 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.rfLinkLevel_value value=100 ack=true
smartgarden.0 | 2022-07-27 11:46:40.645 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.batteryState_timestamp value=2022-07-27T09:39:28.756Z ack=true
smartgarden.0 | 2022-07-27 11:46:40.644 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.batteryState_value value=OK ack=true
smartgarden.0 | 2022-07-27 11:46:40.644 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.batteryLevel_timestamp value=2022-07-27T09:46:40.378Z ack=true
smartgarden.0 | 2022-07-27 11:46:40.644 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.batteryLevel_value value=100 ack=true
smartgarden.0 | 2022-07-27 11:46:40.643 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_COMMON_558f.name_value value=Robert ack=true
smartgarden.0 | 2022-07-27 11:46:40.642 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_MOWER_cbtg.operatingHours_value value=2308 ack=true
smartgarden.0 | 2022-07-27 11:46:40.642 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_timestamp value=2022-07-27T09:39:28.756Z ack=true
smartgarden.0 | 2022-07-27 11:46:40.641 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_value value=PARKED_PARK_SELECTED ack=true
smartgarden.0 | 2022-07-27 11:46:40.640 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_control_i value=null ack=true
smartgarden.0 | 2022-07-27 11:46:40.640 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_mowing_i value=false ack=true
smartgarden.0 | 2022-07-27 11:46:40.640 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_MOWER_cbtg.state_timestamp value=2022-07-27T09:39:28.756Z ack=true
smartgarden.0 | 2022-07-27 11:46:40.640 | info | 3/ sgSetState: sg.0.L_0478.D_558f.S_MOWER_cbtg.state_value value=OK ack=true
smartgarden.0 | 2022-07-27 11:46:40.625 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .rfLinkState_value COMMON ONLINE
smartgarden.0 | 2022-07-27 11:46:40.622 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .modelType_value COMMON GARDENA smart Mower
smartgarden.0 | 2022-07-27 11:46:40.622 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .serial_value COMMON 200709482
smartgarden.0 | 2022-07-27 11:46:40.622 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .rfLinkLevel_timestamp COMMON 2022-07-27T08:44:47.765+00:00
smartgarden.0 | 2022-07-27 11:46:40.622 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .rfLinkLevel_value COMMON 100
smartgarden.0 | 2022-07-27 11:46:40.622 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .batteryState_timestamp COMMON 2022-07-27T09:39:28.756+00:00
smartgarden.0 | 2022-07-27 11:46:40.622 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .batteryState_value COMMON OK
smartgarden.0 | 2022-07-27 11:46:40.621 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .batteryLevel_timestamp COMMON 2022-07-27T09:46:40.378+00:00
smartgarden.0 | 2022-07-27 11:46:40.621 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .batteryLevel_value COMMON 100
smartgarden.0 | 2022-07-27 11:46:40.621 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_COMMON_558f .name_value COMMON Robert
smartgarden.0 | 2022-07-27 11:46:40.621 | info | 3/ setServiceStates: sg.0.L_0478.D_558f.S_COMMON_558f
smartgarden.0 | 2022-07-27 11:46:40.621 | info | 3/ setServiceStates: relationship searching
smartgarden.0 | 2022-07-27 11:46:40.621 | info | 3/ parseMessage: COMMON found
smartgarden.0 | 2022-07-27 11:46:40.614 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_MOWER_cbtg .operatingHours_value MOWER 2308
smartgarden.0 | 2022-07-27 11:46:40.614 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_MOWER_cbtg .activity_timestamp MOWER 2022-07-27T09:39:28.756+00:00
smartgarden.0 | 2022-07-27 11:46:40.613 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_MOWER_cbtg .activity_value MOWER PARKED_PARK_SELECTED
smartgarden.0 | 2022-07-27 11:46:40.613 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_MOWER_cbtg .state_timestamp MOWER 2022-07-27T09:39:28.756+00:00
smartgarden.0 | 2022-07-27 11:46:40.613 | info | 3/ checkAndSetForecast: sg.0.L_0478.D_558f.S_MOWER_cbtg .state_value MOWER OK
smartgarden.0 | 2022-07-27 11:46:40.613 | info | 3/ setServiceStates: sg.0.L_0478.D_558f.S_MOWER_cbtg
smartgarden.0 | 2022-07-27 11:46:40.613 | info | 3/ setServiceStates: relationship searching
smartgarden.0 | 2022-07-27 11:46:40.612 | info | 3/ parseMessage: MOWER found
smartgarden.0 | 2022-07-27 11:44:40.072 | info | 3/ on_pong: ++ pong'ed ++
smartgarden.0 | 2022-07-27 11:42:10.073 | info | 3/ on_pong: ++ pong'ed ++
smartgarden.0 | 2022-07-27 11:40:52.706 | error | Error: request returned 429
smartgarden.0 | 2022-07-27 11:40:52.706 | info | 3/ Mower command failure.response.statusCode/Message=429/
smartgarden.0 | 2022-07-27 11:40:52.706 | info | 3/ Mower command failure, options.url=https://api.smart.gardena.dev/v1/command/29cdb6c5-25b4-491a-9b8a-1739ac8b558f:cbtg
smartgarden.0 | 2022-07-27 11:40:52.706 | info | 3/ request Mower ...
smartgarden.0 | 2022-07-27 11:40:52.460 | error | Error: request returned 429
smartgarden.0 | 2022-07-27 11:40:52.460 | info | 3/ Mower command failure.response.statusCode/Message=429/
smartgarden.0 | 2022-07-27 11:40:52.460 | info | 3/ Mower command failure, options.url=https://api.smart.gardena.dev/v1/command/29cdb6c5-25b4-491a-9b8a-1739ac8b558f:cbtg
smartgarden.0 | 2022-07-27 11:40:52.460 | info | 3/ request Mower ...
smartgarden.0 | 2022-07-27 11:40:52.404 | info | 3/ ---> State change by device: state sg.0.info.RateLimitCounter changed, (ack = true)
smartgarden.0 | 2022-07-27 11:40:52.396 | info | 3/ incrementLimitCounter: new counters : y2022 / m2022-07: 27 / d2022-07-27: 27 / hr09: 15 / last30days: 27 / last31days: 27
smartgarden.0 | 2022-07-27 11:40:52.387 | info | 3/ ---> Command should be sent to device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_control_i changed, 39600 (ack = false)
smartgarden.0 | 2022-07-27 11:40:52.307 | info | 3/ ---> State change by device: state sg.0.info.RateLimitCounter changed, (ack = true)
javascript.0 | 2022-07-27 11:40:52.298 | info | script.js.common.Garten.Robert: Robert 100
`

Die unterste Zeile soll den Roboter starten. 

Ich hoffe jemand wird daraus schlauer als ich.

**Comment by sparrow1990** [comment]
Bekomme auch 429. Log wie folgt:

> 

smartgarden.0 | 2022-07-28 09:47:44.255 | error | Error: request returned 429
-- | -- | -- | --
smartgarden.0 | 2022-07-28 09:47:44.255 | info | 3/ Mower command failure.response.statusCode/Message=429/
smartgarden.0 | 2022-07-28 09:47:44.255 | info | 3/ Mower command failure, options.url=https://api.smart.gardena.dev/v1/command/29cdb6c5-25b4-491a-9b8a-1739ac8b558f:cbtg
smartgarden.0 | 2022-07-28 09:47:44.254 | info | 3/ request Mower ...
smartgarden.0 | 2022-07-28 09:47:44.215 | error | Error: request returned 429
smartgarden.0 | 2022-07-28 09:47:44.215 | info | 3/ Mower command failure.response.statusCode/Message=429/
smartgarden.0 | 2022-07-28 09:47:44.215 | info | 3/ Mower command failure, options.url=https://api.smart.gardena.dev/v1/command/29cdb6c5-25b4-491a-9b8a-1739ac8b558f:cbtg
smartgarden.0 | 2022-07-28 09:47:44.214 | info | 3/ request Mower ...
smartgarden.0 | 2022-07-28 09:47:44.169 | info | 3/ ---> State change by device: state sg.0.info.RateLimitCounter changed, (ack = true)
smartgarden.0 | 2022-07-28 09:47:44.156 | info | 3/ incrementLimitCounter: new counters : y2022 / m2022-07: 170 / d2022-07-28: 65 / hr07: 17 / last30days: 170 / last31days: 170
smartgarden.0 | 2022-07-28 09:47:44.113 | info | 3/ ---> Command should be sent to device: state sg.0.L_0478.D_558f.S_MOWER_cbtg.activity_control_i changed, PARK_UNTIL_FURTHER_NOTICE (ack = false)
smartgarden.0 | 2022-07-28 09:47:44.108 | info | 3/ ---> State change by device: state sg.0.info.RateLimitCounter changed, (ack = true)
javascript.0 | 2022-07-28 09:47:44.053 | info | script.js.common.Garten.Robert: Robert 20

**Comment by XerXes777** [comment]
Ich bekomme auch ständig den fehler 429

**Comment by XerXes777** [comment]
Rate Limits

Rate limits are in place to prevent malicious use of the API that would impact other users.

Applications share a pool of keys that each are assigned certain quota. An application that behaves as a good citizen of the Gardena eco system should not exceed the following limits:

    On average one call every fifteen minutes.
    3'000 requests per month.

These limits should not pose a problem if you use REST calls only to update the state of your location once and then use the real time API to stay in sync (see sections below for more information). If you feel your application absolutely cannot adhere to these limits and your use case is interesting for Gardena, please get in touch to see whether we can grant you higher rate limits.

**Comment by jpgorganizer** [comment]
this is no bug of the adapter, it's related to the Gardena Cloud Server API

**Comment by reutli** [comment]
But could be handled via error handling and trying to repeat commands...?! If a device is responding with error 429 it should be possible to try re-sending, let's say three times and throw error after this try-loop.
just saying ;o)
