### ISSUE TITLE
Status des Mähers wird nicht aktualisiert in bestimmten Situationen

### ISSUE THREAD

**Issue by neopholus** [jpgorganizer/ioBroker.smartgarden#54]
Hallo zusammen,

folgendes funktioniet, wie erwartet:
- In der Gardena APP umschalten z.B. auf "Bis auf weiteres parken"
- Kurz darauf sieht man in den Smartgarden-Logs, dass ein Update verarbeitet wird
- Dann steht im "activity_value" auch der richtige Wert drin, für das Beispiel "PARKED_PARK_SELECTED"

Was nicht (immer) funktioniert:
- Per Javascript-Befehl soll der Activity_Value geändert werden:
`setState('smartgarden.0.LOCATION_XXXX.SERVICE_MOWER_YYYY.activity_control_i', 'PARK_UNTIL_FURTHER_NOTICE')`
- In der Gardena-App wird die Änderung nach kurzer Zeit angezeigt (was bedeutet, dass der Befehlt oben wohl korrekt ist)
- Das Objekt "activity_value" wird allerdings öfters nicht aktualisiert. Wiederholt man den Befehl erneut, wird öfters die Änderung auch in "activity_value" angezeigt.

Es tritt kein Fehler im Log auf!

Hat das Problem noch jemand anders?

Viele Grüße
Stefan

**Comment by neopholus** [comment]
Dieses Log wird angezeigt, wenn das Kommando zwar geschickt wird, aber kein Update des Status des Mähers kommt (die Hex-IDs habe ich maskiert):

`
smartgarden.0 | 2022-08-20 16:04:08.272 | info | 3/  Mower command successful.  options.url=https://api.smart.gardena.dev/v1/command/88888888-4444-4444-4444-BBBBBBBBBBBB  response.statusCode/Message=202/Accepted
-- | -- | -- | --
smartgarden.0 | 2022-08-20 16:04:08.271 | info | 3/ request Mower ...
smartgarden.0 | 2022-08-20 16:04:03.962 | info | 3/ ---> State change by device: state sg.0.info.RateLimitCounter changed,  (ack = true)
smartgarden.0 | 2022-08-20 16:04:03.936 | info | 3/ incrementLimitCounter: new counters : y2022 / m2022-08: 746 / d2022-08-20: 44 / hr14: 2 / last30days: 1411 / last31days: 1411
smartgarden.0 | 2022-08-20 16:04:03.929 | info | 3/  ---> Command should be sent to device: state  sg.0.L_f4db.D_776f.S_MOWER_776f.activity_control_i changed,  PARK_UNTIL_NEXT_TASK (ack = false)
`

Wie es aber halt so ist, jetzt wo ich ein entsprechendes Log dazu erstellen will, funktioniert es reibungslos.
Daher nochmal die Frage: Hat das Verhalten schon jemand anders beobachtet?

**Comment by jpgorganizer** [comment]
This is not an adapter problem. The values are updated if the value change is sent by the Gardena server. If this message does not appear, then there is no update of the value.
