### ISSUE TITLE
Error: request returned 403 Forbidden

### ISSUE THREAD

**Issue by svenover** [jpgorganizer/ioBroker.smartgarden#56]
Hi,

today, I have to restart my Gardena Adapter in ioBroker. 

I got the following error.
`smartgarden.0 | 2023-05-03 15:39:10.277 | error | Error: request returned 403 Forbidden`
`smartgarden.0 | 2023-05-03 15:39:07.249 | info | starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.smartgarden, node: v18.16.0, js-controller: 4.0.24`

I checked the Husqvarna Developer side. My login and the application key is correct.

Any idea, what is going wrong?

**Comment by jpgorganizer** [comment]
Looks like a server problem at Gardena. They may have changed something. Hopefully no adjustments to the adapter are required...we'll wait and see

**Comment by pestho** [comment]
I had the same issue

**Comment by reutli** [comment]
> Looks like a server problem at Gardena. They may have changed something. Hopefully no adjustments to the adapter are required...we'll wait and see

Is the API reachable? As I think to know, the API can be tested directly in the developer portal...

**Comment by svenover** [comment]
Many thanks for all the comments. Then I will wait and I hope the API is working in a few hours.

**Comment by Gundika** [comment]
Have same issue; api token checked but without success :-(
Any idea what happen?

**Comment by ChrAu1202** [comment]
Same for me!

**Comment by boergl** [comment]
Same for me :(

**Comment by shizophren83** [comment]
Same here.

**Comment by engelsofta** [comment]
> Please try to make a new API connection with new credentials! This seems to be the solution! see ioBroker forum [https://forum.iobroker.net/topic/65105/adapter-smartgarden-fehler-403/17](url)

its working again

-> new Application -> Key and Secret in IOBroker -> delete Username and password -> Restart Adapter

**Comment by svenover** [comment]
Hi to all,

I also creasted a new application in Husqvarna Developer Portal and use only the application key and application secret in the ioBroker Gardena Adapter.

Now, all is running well. Many thanks for the workaround.
