### ISSUE TITLE
Fehler 403

### ISSUE THREAD

**Issue by smartprojectsdeveloper** [jpgorganizer/ioBroker.smartgarden#58]

**Comment by engelsofta** [comment]
> Gleiches Problem seit 03.05. ca. 11:30h - gibt es eine Lösung?

Neue Appl. Erstellen und Daten in IOBroker eingeben

**Comment by pellenbeck** [comment]
Ja, hatte ich dann auch hier gelesen und gemacht:
https://forum.iobroker.net/topic/65105/adapter-smartgarden-fehler-403/5?_=1683207342760

Aber das kann ja nicht die Endlösung sein. Aber das muss Gardena/Husqvarna sagen :-)
