### ISSUE TITLE
Error 403 with node 18.16.0

### ISSUE THREAD

**Issue by meanwhile28** [jpgorganizer/ioBroker.smartgarden#59]
Hi Team,

just to let you know I tested the node 18.16.0 yesterday and I receive the error message 403 forbidden.
Falling back to node 16 fixed the issue again.

**Comment by jpgorganizer** [comment]
message code 403 forbidden is an answer from server side. Server doesn't know about node version :-)
This error is currently common among many users. Even with node v16.x.
see https://forum.iobroker.net/topic/65105/adapter-smartgarden-fehler-403/5?_=1683207342760
