### ISSUE TITLE
Anzeige von Kollisionen und anderen Datenpunkten

### ISSUE THREAD

**Issue by neopholus** [jpgorganizer/ioBroker.smartgarden#6]
Hallo,

super Arbeit, funktioniert einwandfrei. Bei dem alten Adapter, den ich genutz habe, wurde die Anzahl der Kollisionen des Mähers angezeigt ("collisions"). Könnte das von diesem Adapter auch als Datenpunkt geliefert werden?

Auch einige andere Datenpunkte würde ich mir wieder wünschen (weil meine Visualisierung darauf aufbaut):
- Status des Empfangs (z.B. "good")

Viele Grüße und Danke
Stefan

**Comment by neopholus** [comment]
Habe gerade in die aktuelle API-Doku geschaut. Beide Datenpunkte sind dort leider gar nicht mehr vorhanden. Können also nicht angezeigt werden.

**Comment by jpgorganizer** [comment]
ja, leider liefert die API nicht mehr  als in den vom Adapter erstellten Datenpunkten. Wenn da mal was dazukommt, dann wird es sofort angezeigt in einem neuen DP

**Comment by jpgorganizer** [comment]
>     * Status des Empfangs (z.B. "good")

das gibt es aber, es gibt einen rfLinkLevel_value, da kannst du dir dein "good" selbst ableiten :-)

**Comment by neopholus** [comment]
Das stimmt, hab ich schon gemacht. Beim alten API kam es direkt zusätzlich als "sprechender Text"... 

Danke!

**Comment by jpgorganizer** [comment]
sprechende Texte sind so eine Sache, da wünscht sich jeder was anderes. Das kann man z.B. in VIS ja gut über ein Binding lösen. Deshalb gibt der Adapter eigentlich nur Werte aus.

Was hast du für Geräte? Einen Mäher und ??? Ich versuche gerade herauszufinden, welche Teile des Adapters eigentlich genutzt werden. Deshalb die Frage.

**Comment by neopholus** [comment]
Ich hab den sprechenden Text auf ein Bild in mediola AIO gemappt. War damals das einfachste.  Umstieg auf VIS steht noch auf der ToDo-Liste. Aber du hast vollkommen Recht. Da will jeder was anderes und ist trivial selbst zu erledigen. 

Ich habe einen Gardena Sileno City 500. Sonst (noch) nichts.
