### ISSUE TITLE
Fehler 403 tritt erneut auf (nach Appl. Neuerstellung)

### ISSUE THREAD

**Issue by Tekklab** [jpgorganizer/ioBroker.smartgarden#61]
Mir ist die "Lösung" über die Neuerstellung der Appl. und Übertragung der neuen Appl. ID & Secret von hier: https://forum.iobroker.net/topic/65105/adapter-smartgarden-fehler-403/5?_=1683207342760
bekannt. Das funktionierte bei mir auch für genau 3 Tage. Heute wieder "Fehler 403". Könnt ihr mal checken, liegt es an mir oder gibts grundsätzlich ein "API Disabling" o.ä. bei zu vielen Requests o.ä.?

P.S. habe jetzt erneut den Fix mit meiner Appl. Erstellung durchgeführt, jetzt funktioniert wieder alles normal, nur wie lange...

**Comment by muhlatte** [comment]
Ist bei mir genau dasselbe, ebenfalls nur 3 Tage am laufen und dann kommt Error 403. Würde mich über eine langfristige Lösung ebenfalls sehr freuen

**Comment by jpgorganizer** [comment]
no problem of adapter - its a Gardena Server problem
