### ISSUE TITLE
GPS-Position is missing in the data points

### ISSUE THREAD

**Issue by christianh17** [jpgorganizer/ioBroker.smartgarden#62]
Hi!
I have two parts of my garden seperatated by a long corridor. Of course I'd like to have both areays mowed, one part is bigger, so it would be nice if one part (the part away from the docking station) would be moved 2 times a day and the part at the docking station once a day. Three moving cycles are esay configurated - via the time, I know how long one cycle + charging lasts.

Sometimes the passage through the corridor does not work and the mover stays in the wrong area. We are not often at home when the mover starts, so I need a monitoring of the area moved. In the documentation I found a hint about getting the position, it says:
```
Position{
latitude	[...]
longitude	[...]
}
```
in the list of schemas. With this data I could do a monitoring and could fine tune the percentage of starts for the two areas.

So: even the documentation says: all data is extracted, is there a change to get the position into the datapoints?

Thx in advance,
tueftler17

**Comment by christianh17** [comment]
Good Morning!
I used the following URL:
https://developer.husqvarnagroup.cloud/apis/automower-connect-api#openapi
Perhaps it is a different API compared to the one which is in use, now?

**Comment by jpgorganizer** [comment]
thats the wrong API, this is for Husqvarna Automower and not for Gardena
