### ISSUE TITLE
Writing a string via Blockly in "duration_value" with ctrl+enter

### ISSUE THREAD

**Issue by hennaschorre** [jpgorganizer/ioBroker.smartgarden#63]
Hello all,

i have problem.
First of all, it is possible to write the string in duration_value with "61" and the keys ctrl+enter (focus of the value) in the objects.
After this, the valve will open for 61 seconds.
Within the 61 seconds, if i will write the string in duration_value with "STOP_UNTIL_NEXT_TASK" and again with ctrl+enter keys, then the valve will close.

How it is possible to write via blockly or something like this, the focused string in the value?
If i write the string "61" or "STOP_UNTIL_NEXT_TASK" via blockly, nothing is working.

Best reggards,
Martin

**Comment by jpgorganizer** [comment]
Hi,
as you wrote, the adapter is working, so there is no issue with it. For this I close this ticket.

I'm not a Blockly-Developer - never used - but maybe I can help anyway.

> it is possible to write the string in duration_value with "61"

have you read the doc
https://github.com/jpgorganizer/ioBroker.smartgarden#for-service_valve and noticed the values you should use? You should use multiples of 60, of course 61 works, but the adapter will use '60`. 



> If i write the string "61" or "STOP_UNTIL_NEXT_TASK" via blockly, nothing is working.

may be you should read https://github.com/jpgorganizer/ioBroker.smartgarden#general-things-to-know-about-data-points


For further help please join [ioBroker forum thread for the adapter](https://forum.iobroker.net/topic/31289/neuer-adapter-smartgarden-adapter-for-gardena-smart-system/) .
