### ISSUE TITLE
Connection == true, wenn Adapter gestoppt

### ISSUE THREAD

**Issue by Standarduser** [jpgorganizer/ioBroker.smartgarden#64]
Wenn die Instanz des Adapters angehalten wird, dann bleibt der State `smartgarden.0.info.connection` auf true, was etwas verwirrend ist. Ich würde es sehr begrüßen, wenn das verhalten so angepasst werden könnte, dass beim Stoppen des Adapters dieser State auf false gehen würde.

Vielen Dank.

**Comment by jpgorganizer** [comment]
fixed with next version
