### ISSUE TITLE
not possible to add application secret

### ISSUE THREAD

**Issue by xmace** [jpgorganizer/ioBroker.smartgarden#65]
unfortunately i'm not able to add application secret in the config page of the adapter.

tried to reinstall the whole adapter, changed application key but i'm not able to click into the section where to add the key.

![image](https://github.com/jpgorganizer/ioBroker.smartgarden/assets/15639172/0fc1ac65-dc46-46fa-a42e-7c5ecea1b2c6)

@Apollon77
can you please have a short look into it?

Thanks a lot

**Comment by Apollon77** [comment]
@jpgorganizer Can oyu please have a look?

**Comment by jpgorganizer** [comment]
the picture shows your error!

Please delete username and password. Only either application secret or username and password can be entered.


see https://github.com/jpgorganizer/ioBroker.smartgarden/blob/master/FAQ.md
