### ISSUE TITLE
"Bad Request" on Mower command

### ISSUE THREAD

**Issue by pellenbeck** [jpgorganizer/ioBroker.smartgarden#68]
@jpgorganizer I would like to re open issue #66 .

I have contacted the Husqvarna Developer Portal with the problem. After exchanging the information about the RateLimitCounter and some log files, I received the following answer from Husqvarna:

Wir können den Fehler reproduzieren, indem Sie «activity_control_i» nur START_SECONDS_TO_OVERRIDE schicken. Sobald Sie diesen Parameter mit einer Zahl konfigurieren (oder Zahl unmittelbar vom command gefolgt), tritt der Fehler nicht mehr auf. Damit können Sie diesen Umstand (der offenbar «nur» diesen Command betrifft) überbrücken, bis ioBroker ggf. zu einem späteren Zeitpunkt das Verhalten für diesen Command korrigiert.

The answer looks to me like a wrong implementation in the adapter or something that can be adjusted in the adapter.
Is there a manual workaround via the adapter?

The problem is that the error "Error: request returned 400 Bad Request" leads to a constant repetition of the requests and thus the RateLimit is exceeded very quickly - which then ends in the error image "Error: request returned 403 Forbidden".

Regards
Philipp

**Comment by jpgorganizer** [comment]
what value do you set in «activity_control_i»?

**Comment by pellenbeck** [comment]
Cannot provide any further logs. I just use the adapter and got those error responses.
Did not set any values by myself.

**Comment by jpgorganizer** [comment]
then I don't understand the issue. If you do not set any values, what's the problem.  I'm closing the issue

> This might be related to my open PR: #67

no

**Comment by jpgorganizer** [comment]
see before

**Comment by pellenbeck** [comment]
I use the adapter "out of the box" and received the documented errors.

Gardena Support reports back what the problem is from their point of view.

Your only thin-lipped answer is then that you do not see the problem in the adapter?
That's not really understandable.

In fact, the problem doesn't really occur with me anymore; if Gardena has fixed something, I can't say.
