### ISSUE TITLE
io-package dependencies is for adapters 

### ISSUE THREAD

**Issue by foxriver76** [jpgorganizer/ioBroker.smartgarden#7]
https://github.com/jpgorganizer/ioBroker.smartgarden/blob/master/io-package.json#L101 makes no sense, please fix it, otherwise js-c 3 won't start your adapter

**Comment by jpgorganizer** [comment]
@foxriver76 
could you please give a link to documentation of io-package.json?
Thanks

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.docs/blob/master/docs/de/dev/objectsschema.md

**Comment by StrathCole** [comment]
@jpgorganizer Die Dependency für die eigenen Module gehören nur in die package.json, die dafür zuständig ist, was als Abhängigkeit für das eigene npm Modul installiert wird. Daher der Fehler, wenn es im io-package.js steht, wo nur die ioB-spezifischen Dinge rein kommen.

**Comment by jpgorganizer** [comment]
gelöst mit v0.5.0

**Comment by foxriver76** [comment]
Thank you
