### ISSUE TITLE
smartgarden has an invalid jsonConfig

### ISSUE THREAD

**Issue by Vippis2000** [jpgorganizer/ioBroker.smartgarden#72]
Getting error 
`Error: request returned 429`

with smartgarden 2.0.0

This appers in log:
`smartgarden has an invalid jsonConfig: [{"instancePath":"/items/tab-main/items/gardena_username","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"visible"},"message":"must NOT have additional properties"},{"instancePath":"/items/tab-main/items/gardena_username","schemaPath":"#/patternProperties/%5E.%2B/allOf/21/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/tab-main","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

It was working well since yesterday. I have controlled valves in my IrrigationControl with Javascript by setting duration_value. Now it stopped working out of nowhere.

Please help!

**Comment by irudi** [comment]
The same problem for me ...

**Comment by jpgorganizer** [comment]
error "invalid jsonConfig" fixed with next version

**Comment by jpgorganizer** [comment]
error "invalid jsonConfig" fixed with next version
