### ISSUE TITLE
Update stable version in repo from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by GermanBluefox** [jpgorganizer/ioBroker.smartgarden#75]
# Think about update stable version to 2.0.1
**Version**: stable=**2.0.0** (727 days old) => latest=**2.0.1** (15 days old)
**Installs**: stable=**2005** (88.29%), latest=**147** (6.47%), total=**2271**

Click to use [developer portal](https://www.iobroker.dev/adapter/smartgarden/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2357)

**Do not close this issue manually as a new issue will be created if condition for update still exists.**

Please drop a comment if any reason exists which blocks updating to version 2.0.1 at this time.

Note: This is an automatically generated message and not personally authored by bluefox!
      @mcm1957 for evidence

**Comment by mcm1957** [comment]
Please note that adding standard GitHub based testing is mandatory.
see https://github.com/jpgorganizer/ioBroker.smartgarden/pull/74
and https://github.com/jpgorganizer/ioBroker.smartgarden/issues/76

If any help is needed pease ping us

**Comment by jpgorganizer** [comment]
There is currently no time for these things. Possibly in November/December or later

**Comment by mcm1957** [comment]
Thanks for showing you motivation to support this adapter.

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 2.0.1 but the current stable version is already 2.0.1.

So this issue should be closed.

@mcm1957 for evidence
