### ISSUE TITLE
Field "Application Secret" is greyed out

### ISSUE THREAD

**Issue by Boronsbruder** [jpgorganizer/ioBroker.smartgarden#79]
When newly installing the adapter, in the settings dialog the field "Application Secret" is greyed-out and can not be filled.
I had to export, edit and import the instance-settings to put in the application-secret.

After that it is showed normally and can be edited.

Admin v7.0.22
js-controller 6.0.9
Node.js: v20.16.0
NPM: 10.8.1

Adapter v2.0.1

**Comment by jpgorganizer** [comment]
I assume you entered something in the username/password field. Remove both and the field will be writable.
Please re-check

**Comment by Boronsbruder** [comment]
Nope.
Screenshot of the freshly installed instance:
![grafik](https://github.com/user-attachments/assets/94935024-7d6d-4240-a292-f50781fa892b)
Nothing filled in!

**Comment by Boronsbruder** [comment]
Problem solved:
I had to delete the prefilled mail@me.com
Then the field is writeable as you told.
