### ISSUE TITLE
Speicherung historischer Daten für Ventile nicht möglich

### ISSUE THREAD

**Issue by gfacek** [jpgorganizer/ioBroker.smartgarden#8]
Aus mir unerfindlichen Gründen ist es nicht möglich mit dem SQL-Adapter historische Daten für Ventile zu speichern. Egal welchen Datenpunkt ich unter einem der Ventile auswähle, ich kann dort nicht das Speichern in SQL aktivieren.
Eine Fehlermeldung ist mir nicht aufgefallen.

**Comment by jpgorganizer** [comment]
und was fang ich nun mit dieser Meldung an?
Entweder mehr Infos, was du gemacht hast usw oder wieder schließen.

**Comment by jpgorganizer** [comment]
bei mir gehts.
![grafik](https://user-images.githubusercontent.com/58396886/80147163-5cc0c980-85b3-11ea-95c4-15f78f2b001d.png)
deshalb schließe ich den Fehler

**Comment by gfacek** [comment]
Zunächst einmal danke für deine Entwicklungsarbeit. Dein Adapter gefällt mir deutlich besser als der "andere".
Ich kann deinem Screenshot jetzt nicht entnehmen, ob du versucht hast das zu aktivieren? Den Schraubschlüssel sehe ich auch jeweils. Beim Gardena-Sensor konnte ich das Speichern in SQL auch aktivieren. Das funktioniert.

Was meine ich mit "aktivieren"?
Hinten auf den Schraubschlüssel
![image](https://user-images.githubusercontent.com/13930186/80187247-945d5f00-860f-11ea-9d78-b83f905b8260.png)

Dann Haken bei "Aktiviert" setzen
![image](https://user-images.githubusercontent.com/13930186/80187308-b35bf100-860f-11ea-888e-4a61039f5a17.png)

Dann unten auf "Speichern"
![image](https://user-images.githubusercontent.com/13930186/80187389-da1a2780-860f-11ea-9925-93a73e910f2f.png)

Wenn man dann erneut reingeht, ist der Haken nicht mehr gesetzt und es wird auch dementsprechend nichts gespeichert.
![image](https://user-images.githubusercontent.com/13930186/80187453-f4ec9c00-860f-11ea-8e0d-03dbb18fda16.png)

Wenn ich im Vergleich die Einstellung für die Temperatur des Gardena-Sensors ansehe, fällt mir auf, dass oben der komplette Datenpunkt-Pfad steht. Das steht in den Einstellungen für die Ventil-Datenpunkte nicht.
![image](https://user-images.githubusercontent.com/13930186/80188008-da66f280-8610-11ea-9558-b96191fdefed.png)

Ich hoffe das war ausführlich genug.

**Comment by jpgorganizer** [comment]
meiner Meinung nach ein Fehler vom History Adapter. Er kommt offensichtlich mit %-Zeichen in der Id nicht klar. Nach den Threads hier im Forum ist das %-Zeichen aber nicht verboten.
Stell dort mal bitte einen Fehler ein.

**Comment by gfacek** [comment]
Welches % in der ID meinst du?
Um nach dem % zu sehen ist mir etwas aufgefallen. Ich dachte vielleicht meinst du ein % innerhalb des Gesamt-Pfades des Datenpunktes. Daher bin ich mal auf Bearbeiten des Datenpunktes gegangen, was ja im Grunde nicht direkt was mit dem History Adapters zu tun hat:
![image](https://user-images.githubusercontent.com/13930186/80199590-cf688e00-8621-11ea-9678-4701f5cf07e4.png)
Dort sind ebenfalls keine Informationen sichtbar. Weder hier....
![image](https://user-images.githubusercontent.com/13930186/80199805-050d7700-8622-11ea-9d69-2e20ebc72f11.png)

...noch unter RAW
![image](https://user-images.githubusercontent.com/13930186/80199885-1d7d9180-8622-11ea-95c4-131590293945.png)

Normal sieht das so aus:
![image](https://user-images.githubusercontent.com/13930186/80199936-30906180-8622-11ea-8c42-690acc2cb1c2.png)

Hast du bei RAW was bei dir stehen? Also bei den Ventilen?

**Comment by jpgorganizer** [comment]
guter Punkt, da habe ich nie reingeschaut. Ich habe gerade eine Frage zu den erlaubten/nicht erlaubten Zeichen in Ids gestellt. Mal sehen, was rauskommt. Das Dumme ist nämlich, dass das %-Zeichen gar nicht das Zeichen ist, das in der Id stehen sollte, sondern eigentlich steht da ein Doppelpunkt, nur ist die ganze Id codiert und da kommen nun die %-Zeichen her. Wenn man nun anders codiert, dann kommt wieder ein anderes Zeichen. Du erkennst das Hamsterrad?

**Comment by jpgorganizer** [comment]
Topic bleibt offen, bis Klärung über erlaubte zeichen vorhanden ist.
siehe https://forum.iobroker.net/topic/32605/erlaubte-zeichen-in-id-s

**Comment by gfacek** [comment]
Ah, jetzt sehe ich auch das % :)
Ja, das % kommt vermutlich von der Umwandlung des Zeichens ":" auf ASCII. %3A ist der Doppelpunkt in der ASCII-Zeichentabelle.

**Comment by gfacek** [comment]
Damit machst du im Irrigation Control Device die Unterscheidung der einzelnen Ventile, richtig? Kann man das nicht mit einem "_" unterscheiden, anstatt des Doppelpunkts?

**Comment by jpgorganizer** [comment]
> Damit machst du im Irrigation Control Device die Unterscheidung der einzelnen Ventile, richtig?

nicht ich, sondern Gardena. Ich hab mir die Ids nicht ausgedacht. Gardena will die wieder zurück, wenn man z.B. startet. Und bei Updates kommt das genau so von Gardena. Somit braucht man eine Codierung die in beide Richtungen funktioniert. Das ist ansich kein Problem, es muss nur klar sein, welche Zeichen kann man nutzen und welche nicht. Wenn das geklärt ist, dann kann das gelöst werden.

**Comment by jpgorganizer** [comment]
wird angepasst, kommt mit der nächsten Version, vmtl. am WoEnde
