### ISSUE TITLE
Use smartgarden Adapter with Automower

### ISSUE THREAD

**Issue by Titus002** [jpgorganizer/ioBroker.smartgarden#85]
Hey, 
I tried to build myself a Automower Control panel but it was not working as good as I hoped it would. Now I want the ioBroker to do all the connection to the API on a RasPi. 
Will there be support for Automowers in future? 
I tried just switching over the connection URL in the Smartgarden settings, but it did not work.

Greetings 
Titus

**Comment by jpgorganizer** [comment]
I'm sorry. Support for automower is not possible.
