### ISSUE TITLE
Restart nach Verbindungsabbruch

### ISSUE THREAD

**Issue by jpgorganizer** [jpgorganizer/ioBroker.smartgarden#9]
Nach einem Abbruch der Internetverbindung und Wiederherstellung sollte automatisch die Verbindung zu Gardena wieder hergestellt werden.

**Comment by JohGrei** [comment]
Hatte heute nach JS-Controller Update wieder Problem beim verbinden. Adapter ging nur auf gelb.
Fehlermeldung war:
` Error: getaddrinfo EAI_AGAIN api.authentication.husqvarnagroup.dev`
Als DNS ist 8.8.8.8 eingetragen. 
Ein Restart half und er verbadn sich sofort..

**Comment by jpgorganizer** [comment]
should be resolved with v1.0.3
